export enum ErrorCodes {
  GENERIC_ERROR = 'GENERIC_ERROR',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  NOT_FOUND = 'NOT_FOUND',
  UPLOAD_INVALID_TYPE = 'UPLOAD_INVALID_TYPE',
  UPLOAD_TOO_LARGE = 'UPLOAD_TOO_LARGE',
  VALIDATION_FAILED = 'VALIDATION_FAILED',
}
